config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  resources :users, only: [:show, :new, :create]
  
  resources :triposts, only: [:show, :new, :create, :edit, :destroy, :update]
  resources :information, only: [:show, :new, :create, :edit, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/destination.rb
class Destination < Category
  has_many :triposts, foreign_key: :destination_id
end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :tripost
  
  validates :time, presence: true
  validates :place, presence: true,length: {maximum: 50}
end

app/models/long.rb
class Long < Category
  has_many :triposts, foreign_key: :long_id
end

app/models/money.rb
class Money < Category
  has_many :triposts, foreign_key: :money_id
end

app/models/status.rb
class Status < Category
  has_many :triposts, foreign_key: :status_id
end

app/models/theme.rb
class Theme < Category
  has_many :triposts, foreign_key: :theme_id
end

app/models/tripost.rb
class Tripost < ApplicationRecord
  belongs_to :user
  has_many :information, dependent: :destroy
  belongs_to :theme
  belongs_to :destination
  belongs_to :long
  belongs_to :money
  belongs_to :status
  
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: {maximum: 50}
  validates :email,presence: true, length: {maximum: 255},
                   format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :triposts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_triposts = user.triposts.count_triposts
  end
  
  
end

app/controllers/information_controller.rb
class InformationController < ApplicationController

  def show
  end

  def new
    @tripost = Tripost.find_by(id: params[:id])
    @information = Tripost.find_by(id: params[:id]).information.build
    @information_all = Tripost.find_by(id: params[:id]).information
  end

  def create
    @information = Tripost.find_by(id: params[:id]).information.build(information_params)
    
    if @information.save
      flash[:success] = "ルートを登録しました"
      redirect_to new_tripost_path
    else
      flash[:danger] = "ルートの登録ができませんでした"
      redirect_to new_tripost_path
    end
  end

  def update
    @information = Information.find(params[:id])
    
    if @information.update(information_params)
      flash[:success]="ルートは正常に更新されました"
      redirect_to new_tripost_path
    else
      flash.now[:danger] = "ルートを更新できませんでした"
      render :edit
    end
  end

  def destroy
    @information = Information.find_by(id: params[:id])
    @information.destroy
    flash[:success] = "ルートを削除しました"
    redirect_back(fallback_location: root_path)
  end

  def edit
    @information = Information.find(params[:id])
    @Tripost = @information.tripost
    @information_all = @Tripost.information
  end
  
  private
  
  def information_params
    params.require(:information).permit(:time, :place, :place_comment, :place_time, :move_by, :move_start, :move_goal, :move_time, :id)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = "今日はどこへ行きますか？"
      redirect_to root_path
    else
      flash[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user  && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  Time.zone = 'Tokyo'
  
  def index
    @user = current_user
    @triposts = Tripost.all.order("created_at desc").page(params[:page])
  end
end


#@user に現在のログインユーザー情報を入れる必要がある

app/controllers/triposts_controller.rb
class TripostsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:destroy]
  
  def show
    @tripost = Tripost.find(params[:id])
    @information = Tripost.find(params[:id]).information.all.order("created_at asc")
  end

  def new
    @tripost = Tripost.new
    @triposts = current_user.triposts.all.order("created_at desc")
  end

  def create
    @tripost = current_user.triposts.build(tripost_params)
    
    if @tripost.save
      flash[:success] = "旅行を登録しました！"
      redirect_to new_tripost_path
    else
      flash[:danger] = "登録に失敗しました。"
      redirect_to new_tripost_path
    end
  end

  def edit
    @tripost = Tripost.find(params[:id])
    @triposts = current_user.triposts.all.order("created_at desc")
  end

  def update
    @tripost = current_user.triposts.find_by(id: params[:id])
    
    if @tripost.update(tripost_params)
      flash[:success] = "旅行を更新しました"
      redirect_to new_tripost_path
    else
      flash.now[:danger] = "旅行を更新できませんでした"
      render "edit"
    end
  end

  def destroy
    @tripost.destroy
    flash[:success] = "旅行を削除しました"
    redirect_back(fallback_location: root_path) 
  end
  
  private
  def tripost_params
    params.require(:tripost).permit(:image, :image_cache, :title,:user_id, :theme_id, :destination_id, :long_id, :money_id, :status_id)
  end
  
  def correct_user
    @tripost = current_user.triposts.find_by(id: params[:id])
    unless @tripost
      redirect_to root_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def show
    @user = User.find(params[:id])
    @triposts = @user.triposts.all.order("created_at desc")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "あなたをトラベラーとして登録しました。"
      redirect_to login_path
    else
      flash.now[:danger] = "登録に失敗しました。"
      render :new
    end    
  end
  
  
  def user_params
    params.require(:user).permit(:name, :email,:password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/information/_information_all.html.erb
<ul class="media-list">
  <% microposts.each do |micropost| %>
    <li class="media">
      <div class="media-body">
        <div>
          <p><%= micropost.id %></p>
          <p><%= micropost.time %></p>
          <p><%= micropost.place %></p>
          <p><%= micropost.place_comment %></p>
          <p><%= micropost.place_time %></p>
          <p><%= micropost.move_by %></p>
          <p><%= micropost.move_start %></p>
          <p><%= micropost.move_goal %></p>
          <p><%= micropost.move_time %></p>
          
          <%# if current_user == micropost.user %>
            <%= link_to "編集", edit_information_path(micropost), class: "btn btn-primary btn-xs" %>
            <%= link_to "削除", micropost , method: :delete, data: {confirm: "You sure?"}, class: "btn btn-danger btn-xs" %>
          <%# end  %>
        </div>
      </div>
    </li>
  <% end %>
  <%# paginate microposts %>
</ul>

app/views/information/_information_tripost.html.erb
<% information.each do |information| %>

  <div class="panel panel-default">
    <div class="panel-heading"><%= information.time %> <%= information.place %> <%= information.place_time %></div>
      <div class="panel-body">
        <p><%= information.place_comment %></p>
      </div>
  </div>
    
  <% unless information.move_start == "" && information.move_goal == "" && information.move_time == "" %>
    <div class="media">
      <div class="media-body">
        <% if information.move_by == "車" %>
          <p> <span class="glyphicon glyphicon-road"></span> <%= information.move_start %><span class="glyphicon glyphicon-chevron-right"></span><%= information.move_goal %></p>
        <% elsif information.move_by =="歩き" %>
            <p> <span class="glyphicon glyphicon-user"></span> <%= information.move_start %><span class="glyphicon glyphicon-chevron-right"></span><%= information.move_goal %></p>
        <% elsif information.move_by =="バス" %>
            <p> <span class="glyphicon glyphicon-bed"></span> <%= information.move_start %><span class="glyphicon glyphicon-chevron-right"></span><%= information.move_goal %></p>
        <% elsif information.move_by =="飛行機" %>
            <p> <span class="glyphicon glyphicon-plane"></span> <%= information.move_start %><span class="glyphicon glyphicon-chevron-right"></span><%= information.move_goal %></p>    
        <% elsif information.move_by =="電車" %>
            <p> <span class="glyphicon glyphicon-queen"></span> <%= information.move_start %><span class="glyphicon glyphicon-chevron-right"></span><%= information.move_goal %></p>
        <% else %>
            <p> <span class="glyphicon glyphicon-briefcase"></span> <%= information.move_start %><span class="glyphicon glyphicon-chevron-right"></span><%= information.move_goal %></p>
        <% end %>
        <p><span class="glyphicon glyphicon-time"></span> <%= information.move_time %></p>
      </div>
    </div>
    <% end %>
    
<% end %>

app/views/information/edit.html.erb
<div class="row">
  <h1>ルート管理画面</h1>

  <div class="col-sm-12 col-md-4 media_back information_back">
    <h1 class="root_h1"><%= @Tripost.title %> <編集中></h1>
    <%= render 'information_all', information: @information_all %>
  </div>

  <div class="col-sm-12 col-md-8">
    <%= render "layouts/form.information", task: @information %>
  </div>

  
</div>

app/views/information/new.html.erb
<div class="row">
  <h1>ルート管理画面</h1>
  
  <div class="col-sm-12 col-md-8 media_back information_back">
    <h1 class="root_h1"><%= @tripost.title %></h1>
    <%= render 'information_all', information: @information_all %>
  </div>

  <div class="col-sm-12 col-md-4">
    <%= render "layouts/form.information", task: @information %>
  </div>

  
</div>

app/views/information/show.html.erb
<h1>Information#show</h1>
<p>Find me in app/views/information/show.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted footer_logo">© 2018 TRIPOST.</div>
</footer>

app/views/layouts/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div class="alert alert-warning"  id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |task| %>
          <li><%= task %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="panel panel-success">
    <div class="panel-heading">旅行を登録する</div>
      <div class="panel-body">
        
  
  <div class="form-group">
    <%= f.label :image, '旅行の画像はありますか？' %>
    <%= f.file_field :image %>
    <% if @tripost.image? %>
　　  <%= image_tag @tripost.image.thumb.url %>
　　  <p>選択していた画像</p>
　   <% else %>
　　  <%= image_tag 'noimage.gif' %>
　   <% end %>
  </div>

  <div class="form-group">
    <%= f.label :title, '今回の旅行は？' %>
    <%= f.text_field :title,class:"form-control" %>    
  </div>
  
  <div class="form-group">
    <%= f.label :theme_id, '旅行のテーマはありますか？' %>
    <%= f.select :theme_id, Theme.all.map{|t| [t.name, t.id] }, {include_blank: false} %>
  </div>

  <div class="form-group">
    <%= f.label :destination_id, "場所はどこですか？" %>
    <%= f.select :destination_id, Destination.all.map{|t| [t.name, t.id] }, {include_blank: false} %>
  </div>
  
  <div class="form-group">
    <%= f.label :long_id, '期間はどのくらいですか？' %>
    <%= f.select :long_id, Long.all.map{|t| [t.name, t.id] }, {include_blank: false} %>
  </div>
  
  <div class="form-group">
    <%= f.label :money_id, '予算はいくらですか？' %>
    <%= f.select :money_id, Money.all.map{|t| [t.name, t.id] }, {include_blank: false} %>
  </div>

  <div class="form-group">
    <%= f.select :status_id, Status.all.map{|t| [t.name, t.id] }, {include_blank: false} %>
  </div>

  <%# unless :image == nil %>
    <%# hidden_field_tag :image, params[:image] %>
  <%# end %>

  <%= f.hidden_field :image_cache %>
  <%= hidden_field_tag :id, params[:id] %>
  
  <%= f.submit '登録',class:"btn btn-primary" %>
<% end %>
  
  
  </div>
      </div>

app/views/layouts/_form.information.html.erb
    <%= form_for(task) do |f| %>
      <% if task.errors.any? %>
        <div class="alert alert-warning"  id="error_explanation">
          <ul>
            <% task.errors.full_messages.each do |task| %>
              <li><%= task %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="panel panel-success">
      <div class="panel-heading">ルートを作成する</div>
      <div class="panel-body">
      
      <div class="form-group"> 
        <%= f.label :time, '時間' %>
        <%= f.select :time,[["06:00", "06:00"], ["06:30", "06:30"], ["07:00", "07:30"], ["08:00", "08:00"], ["08:30", "08:30"], ["09:00", "09:00"], ["09:30", "09:30"], ["10:00", "10:00"], ["10:30", "10:30"], ["11:00", "11:00"], ["11:30", "11:30"], ["12:00", "12:00"], ["12:30", "12:30"], ["13:00", "13:00"], ["13:30", "13:30"], ["14:00", "14:00"], ["14:30", "14:30"], ["15:00", "15:00"], ["15:30", "15:30"], ["16:00", "16:00"], ["16:30", "16:30"], ["17:00", "17:00"], ["17:30", "17:30"], ["18:00", "18:00"], ["18:30", "18:30"], ["19:00", "19:00"], ["19:30", "19:30"], ["20:00", "20:00"], ["20:30", "20:30"], ["21:00", "21:00"], ["21:30", "21:30"], ["22:00", "22:00"], ["22:30", "22:30"], ["23:00", "23:00"], ["23:30", "23:30"], ["24:00", "24:00"]] %>
        <%# f.datetime_select :time, {:discard_year => true,:discard_month => true,:discard_day => true} %>
      </div>
      
      <div class="form-group">
        <%= f.text_field :place,:placeholder => "場所",class:"form-control" %>    
      </div>
    
      <div class="form-group">
        <%= f.text_field :place_comment,:placeholder => "コメント", class:"form-control" %>    
      </div>
      
      <div class="form-group">
        <%= f.text_field :place_time,:placeholder => "滞在時間",class:"form-control" %>    
      </div>
    
      <div class="form-group">
        <%= f.label :move_by, '移動手段' %>
        <%= f.select :move_by,[["歩き", "歩き"], ["バス", "バス"], ["車", "車"], ["飛行機", "飛行機"], ["電車", "電車"], ["その他", "その他"]] %>    
      </div>
      
      <div class="form-group">
        <%= f.text_field :move_start, :placeholder => "発", class:"form-control" %>    
      </div>
      
      <div class="form-group">
        <%= f.text_field :move_goal, :placeholder => "着",class:"form-control" %>    
      </div>
    
      <div class="form-group">
        <%= f.text_field :move_time, :placeholder => "移動時間",class:"form-control" %>    
      </div>
      
      <%= hidden_field_tag :id, params[:id] %>
      <%= f.submit '登録',class:"btn btn-primary" %>
      
      </div>
    </div>
      
    <% end %>
  

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left" href="/"><img src="/images/tripost_logo.png" alt="Tripost"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "旅行登録",new_tripost_path %></li>
          <li><%= link_to "マイページ",user_path(current_user) %></li>
          <li><%= link_to "ログアウト",logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録",signup_path %></li>
          <li><%= link_to "ログイン",login_path %></li>
        <% end %>
      </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Tripost</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

  
  </body>

  <%= render 'layouts/footer' %>
  
</html>

app/views/toppages/_triposts_toppages.html.erb
  <ul class="media-list">
    <% microposts.each do |micropost| %>
        <% if micropost.status.name == "投稿" %>
          <div class="panel panel-default">
            <li class="media">
              <div class="media-left">
                <% if micropost.image? %>
  　　            <%= image_tag micropost.image.thumb.url,class:"thumb_image" %>
                <% end %>
              </div>
              <div class="media-body">
                <div>
                  <span class="text-muted">posted by <%= link_to micropost.user.name, user_path(micropost.user) %></span><span class="text-muted"> posted at <%= micropost.created_at.strftime('%Y/%m/%d') %></span>
                </div>
                <div>
                  <p><%= micropost.title %></p>
                    <%= link_to "詳細", tripost_path(micropost), class: "btn btn-success btn-xs" %>
                </div>
              </div>
            </li>
          </div>
        <% end %>
    <% end %>
    <%# paginate microposts %>
  </ul>

app/views/toppages/index.html.erb
<div class="row">
  <% if logged_in? %>
  <aside class="col-xs-12 col-md-3">
    <div class="panel panel-success">
    	<div class="panel-heading">
		    <img class="media-object img-rounded" src="<%= gravatar_url(current_user, options = { size: 50 }) %>" alt="">
	    </div>
	    <div class="panel-body">
	    	<p><%= @user.name %></p>
        <p><%= link_to "旅行を登録する",new_tripost_path ,class: "btn btn-primary" %></p>
	    </div>
    </div>
  </aside>
  <% end %>
  <div class="col-xs-12 col-md-8">
    <%= render 'triposts_toppages', microposts: @triposts %>
  </div>
</div>

app/views/triposts/_triposts.html.erb
<ul class="media-list">
  <% microposts.each do |micropost| %>
    <div class="panel panel-default">
      <li class="media">
      <div class="media-left">
          <% if micropost.image? %>
　　        <%= image_tag micropost.image.thumb.url, class:"thumb_image" %>
　         <% else %>
　　        <%# image_tag 'noimage.gif',class:"thumb_image" %>
　        <% end %>
      </div>
      <div class="media-body">
        <div>
          <%# link_to micropost.user.name, user_path(micropost.user) %> <span class="text-muted"><%# micropost.created_at %></span>
        </div>
        <div class="tripost">
          <p><%= link_to micropost.title, micropost ,:target=>["_blank"] %></p>
          <div class="label label-default label_tripost"><%= micropost.theme.name %></div>
          <div class="label label-default label_tripost"><%= micropost.destination.name %></div>
          <div class="label label-default label_tripost"><%= micropost.long.name %></div>
          <div class="label label-default label_tripost"><%= micropost.money.name %></div>
          <% if micropost.status.name == "投稿" %>
            <div class="label label-danger label_tripost"><%= micropost.status.name %></div>
          <% else %>
            <div class="label label-primary label_tripost"><%= micropost.status.name %></div>
          <% end %>

          <div class="btn_tripost">
          <% if current_user == micropost.user %>
            <%# link_to "詳細", micropost ,:target=>["_blank"], class: "btn btn-outline-primary btn-xs" %>
            <%= link_to "ルート作成", new_information_path(id: micropost.id), class: "btn btn-success btn-xs" %>
            <%= link_to "編集", edit_tripost_path(micropost), class: "btn btn-primary btn-xs" %>
            <%= link_to "削除", micropost , method: :delete, data: {confirm: "You sure?"}, class: "btn btn-danger btn-xs" %>
          <% end  %>
          </div>
        </div>
      </div>
    </li>
    </div>
  <% end %>
  <%# paginate microposts %>
</ul>

app/views/triposts/edit.html.erb
<div class="row">
  <h1>旅行管理画面</h1>

  <div class="col-sm-12 col-md-8">
    <%= render 'triposts/triposts', microposts: @triposts %>
  </div>

  <div class="col-sm-12 col-md-4">
    <%= render "layouts/form", task: @tripost %>
  </div>

</div>

app/views/triposts/new.html.erb
<div class="row">
  <h1>旅行管理画面</h1>

  <div class="col-sm-12 col-md-8">
    <%= render 'triposts/triposts', microposts: @triposts %>
  </div>

  <div class="col-sm-12 col-md-4">
    <%= render "layouts/form", task: @tripost %>
  </div>
  
</div>

app/views/triposts/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 media_back tripost_content">
  
  <% if @tripost.image? %>
　　<%= image_tag @tripost.image.url,class:"tripost_image" %>
　<%# else %>
　　<%# image_tag 'noimage.gif' %>
　<% end %>
  
  <h1 class="tripost_h1"><%= @tripost.title %></h1>
  
  <div class="category">
  <%# if !@tripost.theme.name.nil? %>
    <div class="label label_show"><%= @tripost.theme.name %><% if !@tripost.theme.name.nil? %><% end %></div>
  <%# end %>
  
  <%# if !@tripost.destination.name.nil? %>
    <div class="label label_show"><%= @tripost.destination.name %></div>
  <%# end %>

  <%# if !@tripost.long.name.nil? %>
    <div class="label label_show"><%= @tripost.long.name %></div>
  <%# end %>  
    
  <%# if !@tripost.money.name.nil? %>
    <div class="label label_show"><%= @tripost.money.name %></div>
  <%# end %>

  </div>

  <%= render 'information/information_tripost', information: @information %>
  
  <% if current_user == @tripost.user %>
    <div class="btn_show">
      <% if @tripost.status.name == "投稿" %>
        <div class="label label-danger label_tripost"><%= @tripost.status.name %></div>
      <% else %>
        <div class="label label-primary label_tripost"><%= @tripost.status.name %></div>
      <% end %>

      <%= link_to '旅行を編集する', edit_tripost_path(@tripost), class: 'btn btn-default' %>
      <%= link_to "ルートを編集する", new_information_path(id: @tripost.id), class: "btn btn-default" %>
    </div>
  <% end %>
  
</div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12 col-md-offset-3 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">新規登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile media_back_user">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
    <p><%= link_to "旅行を登録する",new_tripost_path ,class: "btn btn-primary" %></p>
  </div>
  
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <ul class="nav nav-tabs">
        <li>マイトラベル</li>
      </ul>
        <div class="triplist">
          <%= render 'triposts/triposts', microposts: @triposts %>
        </div>
    </div>
  </div>
  
</div>